### ISSUE TITLE
your minimum sdk is 29 :( please update with and minimum sdk 24

### ISSUE THREAD

**Issue by Khadijaikram** [yassineAbou/Clock#4]

**Comment by yassineAbou** [comment]
Hi Khadijaikram , Thanks for letting me know. I'll get it fixed today.
Fixing this issue is easy! If you'd like to contribute to the project, here's what you can do:
    1-Update the minimum SDK to 24.
    2-In the following files: AlarmWorker, StopwatchWorker, TimerCompletedWorker, and TimerRunningWorker, replace ServiceInfo.FOREGROUND_SERVICE_TYPE_NONE with 0.
